### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Somekabk** [python/devguide#1075]

**Comment by CAM-Gerlach** [comment]
@python/organization-owners Please ban as a spammer; account's entire activity history consists of opening empty spam issues like this (repeatedly on other repos), empty "approve" review on an already merged PRs which is a very common spam tactic we've seen in the past on Python org repos (since it cannot be easily reported) and forking one repo with no changes, for zero non-spam contributions. Therefore, it seems clear it exists for no purpose other than spam.

I also reported to GitHub, of course, and left comments on the other issues mentioning these same findings for the benefit of those repos.
