### ISSUE TITLE
buggy heading numbers

### ISSUE THREAD

**Issue by brettcannon** [python/devguide#11]
Moved from http://bugs.python.org/issue17227

**Comment by matrixise** [comment]
@brettcannon this issue is closed on b.p.o, should we update it ?

**Comment by brettcannon** [comment]
The issue on b.p.o is closed because this issue now supercedes it, so any updates for the issue should happen here.

**Comment by matrixise** [comment]
Hi @brettcannon 

I am not totally sure but I think we can close this issue because all the questions have a good number. https://docs.python.org/devguide/faq.html#communications or http://cpython-devguide.readthedocs.io/en/latest/faq.html?highlight=faq#communications  @willingc could you confirm too ?

Thank you

**Comment by willingc** [comment]
Looks good to me @matrixise. +1 to closing.

**Comment by matrixise** [comment]
thanks for your feedback, and therefore we can close this issue, @brettcannon ? could you close it I don't have the rights. Thank you

**Comment by willingc** [comment]
@matrixise I've gone ahead and closed this. @brettcannon, hope that is ok for you. Perhaps giving @matrixise permissions on this repo would be helpful given the work he has been doing.

**Comment by brettcannon** [comment]
@willingc I actually offered them to him on Sunday at PyCon CA, so the time machine strikes again. 😄 I have gone in and given @matrixise write access, so now he just needs to accept the invite.

**Comment by matrixise** [comment]
Thank you so much. Of course, I have accepted the invitation, Thank you
