### ISSUE TITLE
Translate docs to others language

### ISSUE THREAD

**Issue by eamanu** [python/devguide#152]
I am working to translate the devguide's Python to Spanish.

Do yo think that it is important?

**Comment by brettcannon** [comment]
While I appreciate the thought, @eamanu , I don't think it is important since all communication around the development of Python takes place in English. That means while it might be easier for someone to get started if the doc is in Spanish, someone who doesn't feel comfortable reading English is going to hit a wall very quickly when they try to participate.

**Comment by eamanu** [comment]
That's right  @brettcannon. You let me a good reason. 

Regards!
