### ISSUE TITLE
Clarify that backports should start from the squashed-and-merged commit

### ISSUE THREAD

**Issue by ncoghlan** [python/devguide#238]
After pointing a new contributor to https://docs.python.org/devguide/gitbootcamp.html#backporting-merged-changes to handle their own backport PRs, I discovered that it's currently taking a step for granted: finding the relevant commit to backport from the CPython master branch, rather than squashing your original PR branch locally.

Since we specifically want to use the squashed-and-merged commit so that the backports include the corresponding commit message, we should make that explicit here.

**Comment by ncoghlan** [comment]
Some initial thoughts on how we might improve this:

1. Move https://docs.python.org/devguide/gitbootcamp.html#backporting-merged-changes to be directly after https://docs.python.org/devguide/gitbootcamp.html#accepting-and-merging-a-pull-request
2. Add a note suggesting the following pair of commands:

    git fetch upstream
    git rev-parse ":/bpo-12345"

3. Mention that the relevant commit hash can also be found by looking at the merge notification on the original PR (e.g. https://github.com/python/cpython/pull/2786#event-1173237073 )

**Comment by Mariatta** [comment]
There's a write up about which commit hash to use in [cherry_picker](https://github.com/python/core-workflow/blob/master/cherry_picker/readme.rst#id4) It can be copied over here.

**Comment by terryjreedy** [comment]
I presume 'bpo-1235' is a stand-in for the fork branch the PR is based on.  Once the merge is done, it disappears from the PR (as the PR can no longer be added to using the branch name ;-).  Copying the commit hash available after the PR is merged seems best.  I try to remember to grab it before I start typing the cherry_picker command.  (Which is working quite well for simple backports.)

**Comment by ncoghlan** [comment]
@terryjreedy `git rev-parse ":/bpo-12345"` searches for a commit *message* containing the given string (rather than a branch name) and returns the commit hash(es).

**Comment by NicholasKobald** [comment]
I found the link Mariatta mentioned to be very useful. The reason I ended up doing it the way I did despite seeing that reference, was because I got errors trying to use the final merge commit hash, since I had no correctly set python/cpython to be upstream of my forked repository (and so the hash gave me a `fatal: bad object ..` error.) 

Because of running into that error and not being sure at first how to fix it, I suggest adding the following as well:

Insure the cpython repository is upstream of your forked repository.
```
git remote add upstream https://github.com/python/cpython.git
```
Then, pull the most recent commits to your local machine.
```
git fetch upstream
git rev-parse ":/bpo-12345"
```

The issue I ran into was partially due to not having experience with working with a forked/base repository before, so perhaps the addition I'm suggesting won't help a large enough amount of people to be worth it. In either case, what made me get to the root of the problem quickly (and fix it) was the snippet you provided, so I do believe that would be helpful.
