### ISSUE TITLE
Running Python test suite with checkout build requires command line.

### ISSUE THREAD

**Issue by Mariatta** [python/devguide#280]
In https://devguide.python.org/runtests/, it says:

> If you don’t have easy access to a command line, you can run the test suite from a Python or IDLE shell

According to @haypo in https://bugs.python.org/issue31761#msg304225 this is wrong, it should only be run in command line.

**Comment by Mariatta** [comment]
@serhiy-storchaka [mentioned](https://bugs.python.org/issue31761#msg304273) that running tests from IDLE used to work, but not anymore since [2015](https://bugs.python.org/issue25588).
I'm thinking that we should still update the devguide saying it doesn't work at the moment.
And then we should remember to update it again once [bpo-25588](https://bugs.python.org/issue25588) has been resolved..

**Comment by terryjreedy** [comment]
'from test import autotest' also fails in a python shell, so merely removing 'or IDLE' may not be the right fix.
I will post to https://bugs.python.org/issue31761 when the already failing control run finishes.

**Comment by terryjreedy** [comment]
'Running & Writing Tests' begins with "This document assumes you are working from an in-development checkout of Python".  Can you tell from the git log when that was added, and by who?  I wonder why it begins this section, rather than the document as a whole?  

If we take the statement as true, then the 'document' assumes that one works with a command line.  Hence the alternative would be irrelevant and should be removed.

The reason for its presence is that at one time, it was considered OK for someone with only installed Python, and in a restricted environment, to make contributions to Python on the tracker.  Hence the alternative for running tests.  Changing the contribution policy needs more discussion than us two.

It is a somewhat separate issue that the alternative does not work.  If the policy is that it should work, then we should try to fix it.  If not, the statement, code snippet, and the module should all go.

**Comment by Mariatta** [comment]
> 'Running & Writing Tests' begins with "This document assumes you are working from an in-development checkout of Python". Can you tell from the git log when that was added, and by who? I wonder why it begins this section, rather than the document as a whole?

Added in 2011: 

https://github.com/python/devguide/commit/f3f0b7bae59e134c8935e71d8a105b5cd78bb644#diff-c04a615d0a3d3ced3419675de9c0f66a
