### ISSUE TITLE
There is a typo in unittest.html

### ISSUE THREAD

**Issue by clockzhong** [python/devguide#401]
The unittest.html has the following typo:
..........................
Here we have not provided a runTest() method, but have instead provided two different test methods. Class instances will now each run one of the test_*() methods, with self.widget created and destroyed separately for each instance. When creating an instance we must specify the test method it is to run. We do this by passing the method name in the constructor:
...........................

The "test_*() " should be changed to "test*()" according to the real code implementation in python's unittest now. Even the example codes has "test_", but the underscore:"_" is really not needed for testcase writing.

The same problem found inf the following website:
https://docs.python.org/2/library/unittest.html
https://docs.python.org/2.7/library/unittest.html
https://docs.python.org/3.2/library/unittest.html

**Comment by Mariatta** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by terryjreedy** [comment]
`text_*()` (notice the `*` wildcard) is correct.  It refers to tests methods with names like `test_this` and `test_that`.  Out of context, the rest of the paragraph is unclear, but that would be a different issue.
