### ISSUE TITLE
Python doesn't have any direct way of finding shape of 2 or multi D list?

### ISSUE THREAD

**Issue by asawaswapnil** [python/devguide#461]
Python doesn't have any direct way of finding shape of 2 or multi D list?
I either need to convert it to numpy array or use len statement 2ice, once for list, once for list[0] to find the size. Could there be a function like .shape in numpy directly in python without numpy or any other libraries to import.

**Comment by Mariatta** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/python/core-workflow/issues/11 (python/cpython doesn't have tags).

**Comment by Mariatta** [comment]
No, there's no built-in function in standard library. This tracker is for discussing issues with Python developer's guide (the documentation on how to contribute to Python), and not quite about proposing ideas of the language itself.

Since this can be accomplished in library like numpy, my hunch is there is no urgent need for having this as part of the standard library (adds complexity to codebase, and maintenance burden). But perhaps that's something to be discussed in python-ideas mailing list or bugs.python.org, not here.

Thanks.
