### ISSUE TITLE
Add information about Netlify preview for docs on GitHub PRs

### ISSUE THREAD

**Issue by willingc** [python/devguide#526]
See https://github.com/python/cpython/pull/15288

**Comment by aeros167** [comment]
@willingc This would probably be bested suited for https://devguide.python.org/documenting/ (``documenting.rst``). Since this section would be fairly small, straight forward, and is already well defined do you think it would be a decent candidate for ``good first issue``? 

I wouldn't mind helping with this, but I think it would serve well as a decent introductory issue for contributing to documentation. I'll add the label for now, feel free to remove it though.

**Comment by De-ma** [comment]
Hey! Can I take this issue on? :-)

**Comment by aeros** [comment]
@De-ma Sure! Feel free to work on this, but keep it mind that we may have to wait for the Netlify setup to be completely finished before we can merge the section into the devguide. See https://github.com/python/cpython/pull/15288#issuecomment-524035385. 

From my understanding, someone with access to the Python organization account such as @ewdurbin or @benjaminp has to install the Netlify GitHub App to the organization account and then choose what repositories to authorize it for. This explained in https://www.netlify.com/docs/github-permissions. I know it's at least needed for CPython, but it might useful for others as well.

**Comment by sparkingdark** [comment]
@willingc is this still open or the work is done

**Comment by Mariatta** [comment]
This is outdated. We are no using readthedocs's PR build preview instead of netlify.
