### ISSUE TITLE
Streamline workflow

### ISSUE THREAD

**Issue by willingc** [python/devguide#54]
@brettcannon I'm wondering if we can do away with the `github` branch now or in the future. Since this is likely a good repo to have folks onboard, it might be helpful to follow the more standard workflow of `master` and the PRs get merged into `master`.

Benefits:
- Consistent with many other open source projects
- The submitter of the PR gets credit for the contribution.
- Avoids the extra burden of maintaining two branches and keeping `github` branch synced.

Thoughts?

**Comment by brettcannon** [comment]
Once the GitHub migration occurs we will merge `github` into `master` and then delete the `github` branch. This split workflow is only until GitHub switch so that we don't have to basically toss out the devguide for a few months until the migration occurs as core devs still use it for their own reference. And no one has or will lose credit as I wasn't planning on doing a squash merge when merging the branches together.

One thing we can do is set GitHub to display the `github` branch as the default branch. The other option is to create a `mercurial` branch, do the merge of `github` into `master` now, but that requires updating Read the Docs (which I can manage) and docs.python.org/devguide (which will be quite painful) to point to the `mercurial` branch (IOW I don't really like the latter option).

But since the devguide is actively used by core devs as a reference we can't toss the Mercurial version quite yet. Occasionally merging from `master` into `github` is just going to be a part of life until the GitHub migration happens (and welcome to maintaining multiple branches like CPython 😉 ).

**Comment by willingc** [comment]
Cool. Glad to see it's a temporary thing. If you add me to the RTD maintainers for the devguide, I could easily build multiple branches and have badges/links in the README to have one click access to both versions or really any version.

It would also be good to set up Travis for the build and linkcheck.

**Comment by berkerpeksag** [comment]
I assume `github` branch will be removed by 2017 so I don't think it's worth to deal with serving multiple branches on both rtfd.org and docs.p.o/devguide.

**Comment by willingc** [comment]
@berkerpeksag I agree with you re: docs.p.o. Not a big deal re: RTD, but I don't think it hurts to have RTD build both.

**Comment by brettcannon** [comment]
TRFD already does build both branches, i.e. http://cpython-devguide.readthedocs.io/en/latest/ tracks `master`, http://cpython-devguide.readthedocs.io/en/github/ tracks `github` (switch is in the bottom-right corner).

**Comment by brettcannon** [comment]
Travis is now set up but without linkcheck as it's constantly failing on the URLs from the buildbot page.

**Comment by willingc** [comment]
@brettcannon I'm going to close this as the originator of the issue since I believe that we have resolved this. Thanks for all the work you are doing on the migration too. :cake:
