### ISSUE TITLE
Possible 2 times faster implementation of math.factorial

### ISSUE THREAD

**Issue by davidgfb** [python/devguide#580]
I've found that my implementation of math.factorial could be 2 times faster than the one in the native library. I've found it in https://es.wikipedia.org/wiki/Lisp and translated it to Python. 
It looks like this: 
```
#recursive function
def factorial(n):
    #PREREQUISITE: for integer n > -1
    if n==0: return 1
    else: return n*factorial1(n-1)
```

**Comment by terryjreedy** [comment]
The above is likely only half as fast as the Python iterative version because functions calls are relatively expensive, and even more *slower* than the C-coded math module version.  The English version of the article, https://en.wikipedia.org/wiki/Lisp_(programming_language), has a better discussion of factorial.

In any case, this is off-topic for the devguide.  Try python-list to discuss further.
