### ISSUE TITLE
https://docs.python.org/devguide/ is broken?

### ISSUE THREAD

**Issue by ned-deily** [python/devguide#79]
Looks like some static files aren't being loaded there.  The RTD mirror is OK.

**Comment by berkerpeksag** [comment]
I'm getting 403 when I try to load https://docs.python.org/devguide/_static/jquery.js It looks like something is wrong with the server configuration.

**Comment by ned-deily** [comment]
Yeah, the group id of the files on the server there seems to be wrong.  @birkenfeld or @benjaminp, can you take a look at it?

**Comment by brettcannon** [comment]
I just discovered this today and emailed the infrastructure team to start a discussion about retiring docs.python.org/devguide and moving to Read the Docs (either with the current RTFD site or under a dev.python.org subdomain). With this and the issues moving the devguide over to git I think it's better to try and shift to Read the Docs since they're set up better for managing this sort of thing.

**Comment by brettcannon** [comment]
Since @ewdurbin got this fixed, I'm going to close this.

**Comment by ned-deily** [comment]
Thanks @brettcannon and @ewdurbin!
