### ISSUE TITLE
remove element from list

### ISSUE THREAD

**Issue by moreajit** [python/devguide#908]
Hi Team,
I'm not sure this is bug or not but resolve my issue.
I have one list with integer. I want to remove all odd or even integer from list without using one more list.
I want to reflect this result in same list.

EX: 
1) lis = [1,2,3,3,4,4,4,5,5,5,6,6,6,55,55,77,77,77,77,88,88,88,88]

like that I want to remove odd/even number.
simply I trying to resolve like 

lis = [1,2,3,3,4,4,4,5,5,5,6,6,6,55,55,77,77,77,77,88,88,88,88]
for num in lis:
    if i%2:
        lis.remove(i)
print(lis)

I got following result:
result = [1, 2, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 55, 55, 77, 77, 77, 77, 88, 88, 88, 88]

**Comment by encukou** [comment]
Hello,
This repository is related to developing Python itself. For questions about how to *use* Python, please ask on [Discourse](https://discuss.python.org/c/users/7).

**Comment by terryjreedy** [comment]
@moreajit When you add code blocks to a message on github, put 3 backticks \` on otherwise blank lines above and below the block.  This preserves indents.  This is fairly standard markup and may work on discourse.  Also, copy and paste the code you actually ran.  Do not retype.  What you post above stops with NameError.

**Comment by moreajit** [comment]
```
lis = [1,2,3,3,4,4,4,5,5,5,6,6,6,55,55,77,77,77,77,88,88,88,88]
for num in lis:
    if i%2:
        lis.remove(i)
print(lis)
```

>
