### ISSUE TITLE
Document CPython lifecycle periods of reduced core dev capacity

### ISSUE THREAD

**Issue by arhadthedev** [python/devguide#937]
As one of the core developers [commented](https://github.com/python/cpython/pull/94687#issuecomment-1219227216):

> We are currently busy with 3.11 release. It may take until 3.11.0 final before we come back to this patch.

Hovewer, seeing no publicly visible increase in CPython PRs, I had no idea that the pre-release period (few last betas and all release candidates?) is loaded. Only after becoming aware of current priorities I've got the idea that monthly massive bumping of all my PRs is counterproductive and just reduces the capacity even further.

I believe that such annual hot periods of Python lifetime should be documented in, for example, *Lifecycle of a Pull Request* section of the devguide. Probably, it can be published as a mapping of day&month spans to relevant affairs.

**Comment by terryjreedy** [comment]
I believe the 'we' in Heimes' comment referred pretty specifically to himself and G. Smith.  Your PR is not labelled as 'bugfix' or 'feature'.  Some devs focus on bugfixes during the beta period.  Some devs (including me) are focusing on doc fixes during this first candidate period as that is what can be merged most easily.  Others on final critical bugfixes.  Others seem to be on 'vacation'.  The devguide could point to the annual version cycle as having some effect on dev time, but it is hard to generalize across all of us.

**Comment by ezio-melotti** [comment]
This will also need to be maintained and updated, and someone will have to link it from issues/PRs (possibly as a canned response), since it seems unlikely that contributors will go looking for it in the devguide.  As Terry mentioned, we could point to the annual version cycle, but if contributors are not going to see the pointer then it's kind of moot doing it.

I suggest closing this issue as not planned.
