### ISSUE TITLE
Update main PEP discussion venue from Python-Dev to Discourse

### ISSUE THREAD

**Issue by encukou** [python/devguide#944]
The Steering Council [intends to change the canonical discussion venue from Python-Dev to Discourse](https://mail.python.org/archives/list/python-dev@python.org/thread/VHFLDK43DSSLHACT67X4QA3UZU73WYYJ/).
To make the switch we'll need a PR that updates the Devguide, to be merged with the announcement.
Does anyone want to do it before I get to it?

* Discourse (and common information) should be listed first
* Guide to Discourse itself (Tutorials for new users) should probably be separated from Python-specific usage
* Mailing lists should go after that, common info replaced by references to Discourse
* Any useful usage tips from the thread should be included
* Discourse/discuss.python.org/Discord is confusing very similar to Discord. It would be nice to normalize the *DPO* abbreviation for Discourse or discuss.python.org (after expanded names are introduced of course).

**Comment by AA-Turner** [comment]
> DPO abbreviation for Discourse or discuss.python.org (after expanded names are introduced of course).

Isn't this abbreviation also used for docs.python.org?

A

**Comment by warsaw** [comment]
"DPO" is way too overloaded to be useful.  I think it's better in this case to just spell it out as "Discourse" or "discuss.python.org".

**Comment by encukou** [comment]
I should have mentioned: these are just collected notes. Don't do it if it doesn't make sense.

**Comment by CAM-Gerlach** [comment]
To note, @vsajip 's PR #938 was already merged which updates several of the core devguide sections discussing dev communication channels. However, a careful inspection reveals a number of other places this comes up, particularly in the context of the PEP process. I've opened #945 which updates these accordingly.

One related thing—is the Committers category on Discourse also going to become the primary, canonical place for core dev votes and internal discussion, or is the current split between that and the Python-Committers list going to continue for the immediate future? I mention this as there are several places in the devguide where the Python-Committers email list is mentioned as the canonical place for such things, and I am wondering if that should be updated to (which my PR, as of yet, does not).

> Discourse/discuss.python.org/Discord is confusing very similar to Discord. It would be nice to normalize the DPO abbreviation for Discourse or discuss.python.org (after expanded names are introduced of course).

As mentioned by others, while I can certainly sympathize with the potential for confusion and really wish that the names were more distinct, I don't think making up a new abbreviation is more rather than less clear, especially for the users who are most likely to be confused by it. While unfortunate, the "Python Discourse" seems to be the predominant way that the platform is referred to both in the documentation that mentions it, and more informally by users familiar with it, with discuss.python.org also being used in some contexts. Also, only org members (Triagers, Core Devs, etc) are given access to the Discord, who are generally more familiar with the various communication channels already, so it is less of a concern in practice.

To mitigate this, we have/can:

* At least on first/prominent usage within a unit of text, link to it directly, which avoids most ambiguity about what it refers to
* Include `discuss.python.org` in a parenthetical when it is first introduced
* If necessary, add a short admonition, or just an inline note, specifically calling out that this is _not_ the same as Discord (though the headings themselves of the two have a parenthetical specifically calling out the difference).

> Isn't this abbreviation also used for (or has the potential to be confused with) docs.python.org?

Also, devguide.python.org too, and possibly other things. While the docs aren't commonly called DPO nor the PEP site PPO, etc., if anything this speaks this not being a widely accepted, used and understood naming pattern, which itself is likely to impede rather than aid clarity and reader-friendliness, especially for the newer contributors that the devguide is generally most used by.

**Comment by encukou** [comment]
> One related thing—is the Committers category on Discourse also going to become the primary, canonical place for core dev votes and internal discussion

Votes, yes.
Internal discussion can happen anywhere, really – the goal is to *ensure relevant voices are heard*, and for stuff below PEP-caliber we currently trust core devs to manage that. So no canonical place, but the devguide should try to document existing practice.

> Python Discourse

+1, thanks for thinking it through! Yes, DPO was a bad idea.
As for admonitions, PEP 401's PSU is the gold standard we're aiming for, of course.

**Comment by CAM-Gerlach** [comment]
> Votes, yes.
> Internal discussion can happen anywhere, really – the goal is to ensure relevant voices are heard, and for stuff below PEP-caliber > we currently trust core devs to manage that. So no canonical place, but the devguide should try to document existing practice.

Thanks; I've update the PR accordingly :+1: 

> As for admonitions, PEP 401's PSU is the gold standard we're aiming for, of course.

:laughing:
